FROM clux/muslrust:stable AS chef
LABEL org.opencontainers.image.source=https://github.com/ccolic/actualbudget-backup
USER root
RUN cargo install cargo-chef
WORKDIR /app

FROM chef AS planner
COPY ./Cargo.toml ./
COPY ./src ./src
RUN cargo chef prepare

FROM chef AS builder
COPY --from=planner /app/recipe.json .
RUN cargo chef cook --release --target x86_64-unknown-linux-musl
COPY . .
RUN cargo build --release --target x86_64-unknown-linux-musl

FROM alpine AS runtime
RUN addgroup -S backup && adduser -S backup -G backup
COPY --from=builder /app/target/x86_64-unknown-linux-musl/release/actualbudget-backup /usr/local/bin/
USER backup
CMD ["/usr/local/bin/actualbudget-backup"]
